-- INFO: this config requires lunarvim.org's base config to be installed.
require "user.plugins" -- run :PackerUpdate to istall new plugins

-- plugin configs
require "user.alpha"
require "user.autocommands"
require "user.colorizer"
require "user.dap"
require "user.diffview"
require "user.fidget"
require "user.indent-blankline"
require "user.keys"
require "user.neovide"
require "user.notify"
require "user.navic"
require "user.null-ls"
require "user.nvim-ts-autotag"
require "user.nvimtree"
require "user.options"
require "user.scrollbar"
require "user.terminal"
require "user.telescope"
require "user.todo"
require "user.treesitter"
require "user.ufo"
require "user.harpoon"
