vim.o.guifont = "MesloLGSDZ Nerd Font:h15" --:h<FontSize>
lvim.log.level = "warn"
lvim.format_on_save = true
lvim.colorscheme = "catppuccin"
vim.g.catppuccin_flavour = "mocha"
vim.opt.relativenumber = true
vim.g.syntax_on = true
vim.o.syntax = "on"
lvim.builtin.autopairs.active = false
lvim.builtin.cmp.experimental.ghost_text = true
